import { ProductSheetPreset } from "./presets";
import { ProductSheetStyleConfig } from "./styles";

/** 자동 생성 — scripts/bake-sheet-baseline.mjs */

export const INITIAL_BRAND_STYLES: Record<string, ProductSheetStyleConfig> = {
  "유쏘랩": {
    "bodyPaddingTop": 5,
    "titleMarginBottom": 5,
    "dividerMarginBottom": 4
  } as ProductSheetStyleConfig
};

export const INITIAL_CARD_STYLES: Record<string, ProductSheetStyleConfig> = {};

export const INITIAL_SHEET_PRESETS: ProductSheetPreset[] = [
  {
    "id": "sheet-preset_mr58ihhtj2zlb",
    "name": "시트 스타일",
    "category": "시트 스타일",
    "style": {
      "cellWidth": 201,
      "cellHeight": 147,
      "width": 188,
      "height": 125,
      "borderRadius": 9,
      "borderWidth": 2,
      "borderColor": "#d1d1d1",
      "backgroundColor": "#ffffff",
      "headerBackgroundColor": "#f6f7f9",
      "dividerColor": "#9aa3af",
      "brandFontSize": 15,
      "brandColor": "#111827",
      "lineFontSize": 15,
      "lineColor": "#111827",
      "categoryColor": "#9aa3af",
      "titleFontSize": 15,
      "titleColor": "#111827",
      "highlightFontSize": 15,
      "highlightColor": "",
      "tagFontSize": 10,
      "tagColor": "#111827",
      "bottomFontSize": 8,
      "bottomColor": "#1f2937",
      "priceFontSize": 15,
      "priceColor": "",
      "headerRowHeight": 22,
      "bodyPaddingX": 15,
      "bodyPaddingY": 8,
      "bodyPaddingTop": 2,
      "accentLineWidth": 2,
      "accentLinePercent": 50,
      "accentColor": "",
      "accentLineOffsetX": 0,
      "lineAccentColor": "",
      "lineAccentWidth": 0,
      "lineAccentPercent": 0,
      "lineAccentOffsetX": 0,
      "titleMarginBottom": 0,
      "dividerMarginBottom": 2,
      "tagLineGap": 2,
      "tagPriceGap": 0,
      "pricePinBottom": 1,
      "titleSingleLine": false,
      "topLineHeight": 2,
      "thickTopLineHeight": 3
    },
    "savedAt": "2026-07-03T17:56:03.473Z"
  },
  {
    "id": "sheet-preset_mr58eyaen4gn6",
    "name": "시트 스타일",
    "category": "시트 스타일",
    "style": {
      "cellWidth": 201,
      "cellHeight": 147,
      "width": 188,
      "height": 150,
      "borderRadius": 9,
      "borderWidth": 2,
      "borderColor": "#d1d1d1",
      "backgroundColor": "#ffffff",
      "headerBackgroundColor": "#f6f7f9",
      "dividerColor": "#9aa3af",
      "brandFontSize": 15,
      "brandColor": "#111827",
      "lineFontSize": 15,
      "lineColor": "#111827",
      "categoryColor": "#9aa3af",
      "titleFontSize": 15,
      "titleColor": "#111827",
      "highlightFontSize": 15,
      "highlightColor": "",
      "tagFontSize": 10,
      "tagColor": "#111827",
      "bottomFontSize": 8,
      "bottomColor": "#1f2937",
      "priceFontSize": 15,
      "priceColor": "",
      "headerRowHeight": 22,
      "bodyPaddingX": 15,
      "bodyPaddingY": 8,
      "bodyPaddingTop": 5,
      "accentLineWidth": 2,
      "accentLinePercent": 50,
      "accentColor": "",
      "accentLineOffsetX": 0,
      "lineAccentColor": "",
      "lineAccentWidth": 0,
      "lineAccentPercent": 0,
      "lineAccentOffsetX": 0,
      "titleMarginBottom": 5,
      "dividerMarginBottom": 4,
      "tagLineGap": 2,
      "tagPriceGap": 2,
      "pricePinBottom": 0,
      "titleSingleLine": false,
      "topLineHeight": 2,
      "thickTopLineHeight": 3
    },
    "savedAt": "2026-07-03T17:53:18.614Z"
  },
  {
    "id": "sheet-preset_mr5893y3cdm0t",
    "name": "시트 스타일",
    "category": "시트 스타일",
    "style": {
      "cellWidth": 201,
      "cellHeight": 147,
      "width": 188,
      "height": 125,
      "borderRadius": 9,
      "borderWidth": 2,
      "borderColor": "#d1d1d1",
      "backgroundColor": "#ffffff",
      "headerBackgroundColor": "#f6f7f9",
      "dividerColor": "#9aa3af",
      "brandFontSize": 15,
      "brandColor": "#111827",
      "lineFontSize": 15,
      "lineColor": "#111827",
      "categoryColor": "#9aa3af",
      "titleFontSize": 15,
      "titleColor": "#111827",
      "highlightFontSize": 15,
      "highlightColor": "",
      "tagFontSize": 10,
      "tagColor": "#111827",
      "bottomFontSize": 8,
      "bottomColor": "#1f2937",
      "priceFontSize": 14,
      "priceColor": "",
      "headerRowHeight": 22,
      "bodyPaddingX": 15,
      "bodyPaddingY": 8,
      "bodyPaddingTop": 3,
      "accentLineWidth": 3,
      "accentLinePercent": 50,
      "accentColor": "",
      "accentLineOffsetX": 0,
      "lineAccentColor": "",
      "lineAccentWidth": 0,
      "lineAccentPercent": 0,
      "lineAccentOffsetX": 0,
      "titleMarginBottom": 4,
      "dividerMarginBottom": 4,
      "tagLineGap": 1,
      "tagPriceGap": 1,
      "pricePinBottom": 1,
      "titleSingleLine": false,
      "topLineHeight": 2,
      "thickTopLineHeight": 3
    },
    "savedAt": "2026-07-03T17:48:46.011Z"
  },
  {
    "id": "sheet-preset_mr57qf1dfo29e",
    "name": "시트 스타일",
    "category": "시트 스타일",
    "style": {
      "cellWidth": 201,
      "cellHeight": 147,
      "width": 188,
      "height": 125,
      "borderRadius": 9,
      "borderWidth": 2,
      "borderColor": "#d1d1d1",
      "backgroundColor": "#ffffff",
      "headerBackgroundColor": "#f6f7f9",
      "dividerColor": "#9aa3af",
      "brandFontSize": 15,
      "brandColor": "#111827",
      "lineFontSize": 15,
      "lineColor": "#111827",
      "categoryColor": "#9aa3af",
      "titleFontSize": 15,
      "titleColor": "#111827",
      "highlightFontSize": 15,
      "highlightColor": "",
      "tagFontSize": 10,
      "tagColor": "#111827",
      "bottomFontSize": 8,
      "bottomColor": "#1f2937",
      "priceFontSize": 15,
      "priceColor": "",
      "headerRowHeight": 22,
      "bodyPaddingX": 15,
      "bodyPaddingY": 8,
      "bodyPaddingTop": 5,
      "accentLineWidth": 2,
      "accentLinePercent": 50,
      "accentColor": "",
      "accentLineOffsetX": 0,
      "lineAccentColor": "",
      "lineAccentWidth": 0,
      "lineAccentPercent": 0,
      "lineAccentOffsetX": 0,
      "titleMarginBottom": 5,
      "dividerMarginBottom": 4,
      "tagLineGap": 2,
      "tagPriceGap": 2,
      "pricePinBottom": 0,
      "titleSingleLine": false,
      "topLineHeight": 2,
      "thickTopLineHeight": 3
    },
    "savedAt": "2026-07-03T17:34:13.921Z"
  }
];
