import { ProductSheetCardData, ProductSheetCardInput } from "./types";

function withIds(items: ProductSheetCardInput[]): ProductSheetCardData[] {
  return items.map((item, i) => ({ id: `sheet-${i + 1}`, ...item }));
}

/** 브라우저에 저장된 시트 데이터 기준 (자동 생성 — scripts/bake-sheet-baseline.mjs) */
const RAW: ProductSheetCardInput[] = [
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 미스",
    tags: ["#보습 #진정 #영양","#티트리추출물함유"],
    bottom: "150ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 크림",
    tags: ["#재생 No.1(델타이드33종)","#PDRN #EGF #글루타티온"],
    bottom: "50ml / 250ml",
    price: "35,000원 / 98,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 마스크팩",
    tags: ["#피부안정 #식물성워터","#PDRN #수분생기"],
    bottom: "150ml",
    price: "35,000원 (10팩)",
    color: "repair",
  },
  {
    brand: "도미나 크림 2% 40g",
    title: "",
    highlight: "색소 침착",
    tags: ["#기미 주근깨","#소용량(g당 625원)"],
    price: "25,000원",
    color: "black",
  },
  {
    brand: "Dr'life",
    line: "HAEYO",
    title: "안틀레이 스틱",
    highlight: "",
    tags: ["#튼살전용 창상피복제","#튼살, 가려움 개선","#편리한 스틱형태"],
    price: "30,000원",
    color: "sun",
  },
  {
    brand: "Dr'life",
    line: "HAEYO",
    title: "안틀레이 스틱",
    highlight: "",
    tags: ["#튼살전용 창상피복제","#튼살, 가려움 개선","#편리한 스틱형태"],
    price: "30,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 앰플",
    tags: ["#재생 No.1(델타이드34종)","#PDRN #병풀 #판테놀"],
    bottom: "50ml",
    price: "45,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 아이크림",
    tags: ["#고보습케어 #피부장벽강화","#피부탄력&미백&진정"],
    bottom: "30ml / 100ml",
    price: "48,000원 / 70,000원",
    color: "repair",
  },
  {
    brand: "도미나 크림 4% 50g",
    title: "",
    highlight: "색소 침착",
    tags: ["#기미 주근깨","#중용량(g당 700원)"],
    price: "35,000원",
    color: "black",
  },
  {
    brand: "이지에프 새살 연고",
    line: "",
    title: "피부 재생",
    highlight: "",
    tags: ["#EGF #쓰레오이드 #흉창생제","#재조합인간상피세포성장인자"],
    price: "18,000원",
    color: "egf",
  },
  {
    brand: "이지에프 새살 연고",
    line: "",
    title: "피부 재생",
    highlight: "",
    tags: ["#EGF #쓰레오이드 #흉창생제","#재조합인간상피세포성장인자"],
    price: "18,000원",
    color: "egf",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 미스트",
    tags: ["#화장전 피부결 정돈 #영양","#피부 보습효과 #피부 탄력관리"],
    bottom: "150ml",
    price: "32,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 토너",
    tags: ["#PDRN #병풀 #판테놀","#탄력&수분&윤기 #쿨링관리"],
    bottom: "1,000ml",
    price: "70,000원",
    color: "repair",
  },
  {
    brand: "도미나 크림 4% 60g",
    title: "",
    highlight: "색소 침착",
    tags: ["#기미 주근깨","#대용량(g당 633원)"],
    price: "38,000원",
    color: "black",
  },
  {
    brand: "노드라나",
    title: "",
    highlight: "피부건조증",
    tags: ["#피부 건조증에 효과적인","#헤파리노이드 #알란토인","#글리시리진산이칼륨"],
    price: "18,000원",
    color: "red",
  },
  {
    brand: "노드라나",
    title: "",
    highlight: "피부건조증",
    tags: ["#피부 건조증에 효과적인","#헤파리노이드 #알란토인","#글리시리진산이칼륨"],
    price: "18,000원",
    color: "red",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 로션",
    tags: ["#PDRN #병풀 #판테놀","#진정효과 #피부장벽강화 #피부보습"],
    bottom: "500ml",
    price: "85,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "케이 크림",
    tags: ["#관리후 피부 진정(델타이드31종)","#K3 #세라마이드 #시아버터"],
    bottom: "50ml / 500ml",
    price: "50,000원 / 120,000원",
    color: "k",
  },
  {
    brand: "멜라토닝 크림 2% 30g",
    line: "",
    title: "색소 침착(히드로퀴논)",
    highlight: "",
    tags: ["#기미 주근깨","#대용량(g당 600원)"],
    price: "18,000원",
    color: "purple",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "포밍 케이 클렌저",
    tags: ["#복합히알루론산 #병풀 #마데카소","#촉촉한 클렌징 #말끔한 클렌징"],
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "포밍 케이 클렌저",
    tags: ["#복합히알루론산 #병풀 #마데카소","#촉촉한 클렌징 #말끔한 클렌징"],
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "케이 앰플",
    tags: ["#관리후 피부 진정(델타이드31종)","#K3 #세라마이드 #시아버터"],
    bottom: "30ml",
    price: "50,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "베리어 케이 미스트",
    tags: ["#지친 피부에 활력","#K3 #밸런스 #보습 #콜라겐생성"],
    bottom: "150ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "멜라토닝 크림 2% 50g",
    line: "",
    title: "색소 침착(히드로퀴논)",
    highlight: "",
    tags: ["#기미 주근깨","#대용량(g당 560원)"],
    price: "28,000원",
    color: "purple",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 미스트",
    tags: ["#지친 피부에 활력","#K3 #밸런스 #보습 #콜라겐생성"],
    price: "35,000원 (10팩)",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 미스트",
    tags: ["#지친 피부에 활력","#K3 #밸런스 #보습 #콜라겐생성"],
    price: "35,000원 (10팩)",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 솔루션",
    tags: ["#피부컨디션저하 시 #마데카소","#구아이아줄렌 #병풀 #어성초"],
    bottom: "120ml",
    price: "90,000원",
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 크림",
    tags: ["#피부컨디셔닝 #생기있는피부","#피부톤개선 #영양충전 #아줄렌","#PDRN #어성초"],
    bottom: "70ml",
    price: "85,000원",
    color: "cica",
  },
  {
    brand: "멜라노사 크림 4% 30g",
    line: "",
    title: "색소 침착(히드로퀴논)",
    highlight: "",
    tags: ["#기미 주근깨","#고함량"],
    price: "20,000원",
    color: "purple",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 솔루션",
    tags: ["#피부컨디션저하시 #마데카소","#구아이아줄렌 #병풀 #어성초"],
    bottom: "120ml",
    price: "90,000원",
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 크림",
    tags: ["#피부컨디셔닝 #생기있는피부","#피부톤개선 #영양충전 #아줄렌","#PDRN #어성초"],
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 앰플",
    tags: ["#피부 진정&쿨링","#피부속까지 수분영양"],
    bottom: "50ml / 500ml",
    price: "45,000원 / 130,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 크림",
    tags: ["#피부각질 진정 개선 #보습","#탄력 #밸런스 유지 #미백"],
    bottom: "250ml",
    price: "98,000원",
    color: "hyaluron",
  },
  {
    brand: "프로캄 레드엑스 크림",
    line: "",
    title: "붓기+멍든곳",
    highlight: "",
    tags: ["#눈가사용 #다크서클 #유아사용","#혈행개선 #비타민K3"],
    price: "12,000원",
    color: "blueDark",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 미스트",
    tags: ["#구아이아줄렌 #수분충전","#쿨링 #진정 #영양보충"],
    price: "35,000원 (10팩)",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 미스트",
    tags: ["#구아이아줄렌 #수분충전","#쿨링 #진정 #영양보충"],
    price: "35,000원 (10팩)",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 마스크팩",
    tags: ["#레이저시술후 #건조한","#쿨링 #주름개선"],
    price: "35,000원 (10팩)",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "히알루론 크림",
    tags: ["#발림성 좋은 #꽉채운보습","#구아이아줄렌 #나이아신"],
    bottom: "50ml",
    price: "40,000원",
    color: "hyaluron",
  },
  {
    brand: "프로캄 후시메디리페어 크림",
    line: "",
    title: "상처 재생",
    highlight: "",
    tags: ["#피부장벽 개선","#저자극 손상 회복"],
    price: "15,000원",
    color: "blueDark",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "히알루론 크림",
    tags: ["#발림성 좋은 #꽉채운보습","#구아이아줄렌 #나이아신"],
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "히알루론 크림",
    tags: ["#발림성 좋은 #꽉채운보습","#구아이아줄렌 #나이아신"],
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "모이스처라이징 클렌저",
    tags: ["#노폐물제거 #진정 #쿨링","#세안 후 촉촉함 #구아이아줄렌"],
    bottom: "150ml",
    price: "28,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "히알루론 크림",
    tags: ["#발림성 좋은 #꽉채운보습","#구아이아줄렌 #나이아신"],
    bottom: "50ml",
    price: "40,000원",
    color: "hyaluron",
  },
  {
    brand: "프로캄 선 에센스",
    line: "",
    title: "백탁 끈적임 NO",
    highlight: "",
    tags: ["#SPF50+ / PA++++","#비타민D 유도체 함유"],
    price: "18,000원",
    color: "blueDark",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "히알루론 크림",
    tags: ["#발림성 좋은 #꽉채운보습","#구아이아줄렌 #나이아신"],
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "히알루론 크림",
    tags: ["#발림성 좋은 #꽉채운보습","#구아이아줄렌 #나이아신"],
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "선블럭",
    highlight: "",
    tags: ["#SPF50+/PA++++ #혼합자차","#자외선차단&피부손상예방","#가볍고 산뜻하게"],
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "브라이트닝 블리칭 앰플",
    highlight: "",
    tags: ["#멜라닌억제(델타이드34종)","#알부틴 #레몬추출물","#나이아신 #글루타티온"],
    bottom: "50ml/500ml",
    color: "sun",
  },
  {
    brand: "HANMI",
    line: "PRO-CALM",
    title: "판테놀 립에센스(튜브)",
    highlight: "",
    tags: ["#판테놀 #알란토인","#거칠고 건조한 입술에","듬~뿍 영양공급"],
    price: "6,000원",
    color: "hanmi",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "브라이트닝 블리칭 앰플",
    highlight: "",
    tags: ["#멜라닌억제(델타이드34종)","#알부틴 #레몬추출물","#나이아신 #글루타티온"],
    color: "sun",
  },
  {
    brand: "종근당",
    line: "",
    title: "더마365 부스터샷 5000",
    highlight: "",
    tags: ["#리들샷","#피부 컨디셔닝 부스터","#피부 자극 테스트 완료"],
    color: "ckdPink",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브 리제너레이트",
    highlight: "레티놀 크림",
    tags: ["#안티에이징 #모공탄력","#PDRN #순수비타민A"],
    color: "retinol",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브 리제너레이트",
    highlight: "레티놀 앰플",
    tags: ["#주름개선 #모공탄력 #안티에이징","#턴오버주기 #세포재생주기"],
    color: "retinol",
  },
  {
    brand: "HANMI",
    line: "PRO-CALM",
    title: "판테놀 립밤(스틱)",
    highlight: "",
    tags: ["#판테놀 #시아버터","#미백+주름개선&자외선차단"],
    price: "6,500원",
    color: "hanmi",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브 리제너레이트",
    highlight: "레티놀 앰플",
    tags: ["#주름개선 #모공탄력 #안티에이징","#턴오버주기 #세포재생주기"],
    color: "retinol",
  },
  {
    brand: "종근당",
    line: "",
    title: "더마그랩 PDRN크림",
    highlight: "",
    tags: ["#PDRN 800ppm","#덱스판테놀 #피부재생 #영양공급"],
    bottom: "10g/30g",
    color: "ckdGreen",
  },
];

export const INITIAL_PRODUCT_SHEET_CARDS = withIds(RAW);

export const PRODUCT_SHEET_CARD_COUNT = INITIAL_PRODUCT_SHEET_CARDS.length;
