import { ProductSheetCardData, ProductSheetCardInput } from "./types";

function withIds(items: ProductSheetCardInput[]): ProductSheetCardData[] {
  return items.map((item, i) => ({ id: `sheet-${i + 1}`, ...item }));
}

/** 브라우저에 저장된 시트 데이터 기준 (자동 생성 — scripts/bake-sheet-baseline.mjs) */
const RAW: ProductSheetCardInput[] = [
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 로션",
    tags: ["#화사한 피부빛","#맑은 생기","#피부 보습효과","#피부 탄력관리"],
    bottom: "150ml",
    price: "85,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 마스크팩",
    tags: ["#피부진정","#보습활력강화","#수분생기"],
    bottom: "1매 / 10매",
    price: "4,000원 (1매) / 35,000원 (10매)",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 미스트",
    tags: ["#화사한 피부빛","#맑은 생기","#피부 보습효과","#피부 탄력관리"],
    bottom: "100ml",
    price: "32,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 아이크림",
    tags: ["#고보습","#피부장벽강화"],
    bottom: "30ml / 100ml",
    price: "48,000원 (30ml) / 70,000원 (100ml)",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 앰플",
    tags: ["#재생 No.1","#PDRN","#앰플"],
    bottom: "10ml / 50ml",
    price: "45,000원 (10ml) / 120,000원 (50ml)",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 토너",
    tags: ["#PDRN","#보습","#피부결","#보습","#영양","#수분유지"],
    bottom: "1,000ml",
    price: "70,000원",
    color: "black",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 크림",
    tags: ["#재생 No.1","#멀티비타민","#PDRN","#EGF","#글루타치온"],
    bottom: "15ml / 200ml",
    price: "35,000원 (15ml) / 98,000원 (200ml)",
    color: "black",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "클렌징 토너",
    tags: ["#미백","#보습","#클렌징스폰지"],
    bottom: "1,000ml",
    price: "70,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 인텐시브",
    highlight: "에이씨 부스터",
    tags: ["#미백","#보습","#클렌징스폰지"],
    bottom: "15ml",
    price: "23,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 인텐시브",
    highlight: "에이씨 크림",
    tags: ["#지성용","#진정","#수분보충"],
    bottom: "15ml",
    price: "23,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브 리네이처레이션",
    highlight: "레티놀 크림",
    tags: ["#안티에이징","#순수비타민A","#PDRN"],
    bottom: "30ml",
    price: "85,000원",
    color: "retinol",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "베리어 케어 미스트",
    tags: ["#지친 피부에 활력","#K3","#밸런스","#보습","#물광피부완성"],
    bottom: "100ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 로션",
    tags: ["#마데카소사이드","#보습","#진정"],
    bottom: "500ml",
    price: "80,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 미스트",
    tags: ["#티트리추출물","#진정","#보습"],
    bottom: "100ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 앰플",
    tags: ["#병풀","#편백수","#피지조절유출"],
    bottom: "20ml / 200ml",
    price: "45,000원 (20ml) / 130,000원 (200ml)",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 클렌저",
    tags: ["#티트리추출물","#피지생성조절"],
    bottom: "1,000ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 토너",
    tags: ["#티트리추출물","#피부안정","#보습"],
    bottom: "1,000ml",
    price: "70,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "케이 앰플",
    tags: ["#병풀추출","#미백","#5가지 펩타이드"],
    bottom: "20ml / 200ml",
    price: "50,000원 (20ml) / 130,000원 (200ml)",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "케이 크림",
    tags: ["#피부진정","#피지추출물","#펩타이드"],
    bottom: "20ml / 200ml",
    price: "50,000원 (20ml) / 120,000원 (200ml)",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "포밍 케어 클렌저",
    tags: ["#지성 미세홈로션","#생기마스크","#자극적 클렌징","#풍부한 클렌징"],
    bottom: "120ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 솔루션",
    tags: ["#피부컨디션 최적화","#마데카소","#구아이아줄렌","#보습","#피부재생"],
    bottom: "120ml",
    price: "90,000원",
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 크림",
    tags: ["#피부개선","#영양충전","#아줄렌","#PDRN","#보습"],
    bottom: "70ml",
    price: "85,000원",
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 로션",
    tags: ["#히알루론산","#수분충전","#피부보습"],
    bottom: "500ml",
    price: "130,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 미스트",
    tags: ["#쿨링","#진정","#보습"],
    bottom: "150ml",
    price: "32,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 앰플",
    tags: ["#천연보습인자","#수분충전","#피부보습"],
    bottom: "20ml / 200ml",
    price: "45,000원 (20ml) / 130,000원 (200ml)",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 크림",
    tags: ["#진정","#보습","#탄력","#밸런스유지"],
    bottom: "50ml / 200ml",
    price: "40,000원 (50ml) / 95,000원 (200ml)",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 토너",
    tags: ["#천연보습인자","#진정","#앰플"],
    bottom: "1,000ml",
    price: "70,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "클렌징 로션",
    tags: ["#미백","#보습","#클렌징스폰지"],
    bottom: "500ml",
    price: "85,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "클렌징 미스트",
    tags: ["#미백기능성","#콜라겐생성","#비타민C"],
    bottom: "150ml",
    price: "32,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "클렌징 앰플",
    tags: ["#멜라닌 억제","#브라이트닝 24시간"],
    bottom: "20ml / 500ml",
    price: "45,000원 (20ml) / 130,000원 (500ml)",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 인텐시브",
    highlight: "블레미쉬 밤",
    tags: ["#피부 케어","#영양보충","#수분보충"],
    bottom: "50ml",
    price: "50,000원",
    color: "black",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브 리네이처레이션",
    highlight: "레티놀 앰플",
    tags: ["#주름개선","#모공관리","#안티에이징","#면역력주기","#세포재생주기"],
    bottom: "30ml",
    price: "85,000원",
    color: "retinol",
  },
];

export const INITIAL_PRODUCT_SHEET_CARDS = withIds(RAW);

export const PRODUCT_SHEET_CARD_COUNT = INITIAL_PRODUCT_SHEET_CARDS.length;
