import { ProductSheetCardData, ProductSheetCardInput } from "./types";

function withIds(items: ProductSheetCardInput[]): ProductSheetCardData[] {
  return items.map((item, i) => ({ id: `sheet-${i + 1}`, ...item }));
}

/** 브라우저에 저장된 시트 데이터 기준 (자동 생성 — scripts/bake-sheet-baseline.mjs) */
const RAW: ProductSheetCardInput[] = [
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 미스트",
    tags: ["#화장전 피부결 정돈 #영양","#피부 보습효과 #피부 탄력관리"],
    bottom: "150ml",
    price: "32,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 앰플",
    tags: ["#재생 No.1 #PDRN #병풀"],
    bottom: "50ml/500ml",
    price: "45,000원/120,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 인센티브",
    highlight: "에이씨 부스터",
    tags: ["#미백 #보습 #진정 #뺄런스유지"],
    bottom: "15ml",
    price: "23,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "블리칭 토너",
    tags: ["#미백 #보습 #진정 #뺄런스유지"],
    bottom: "1000ml",
    price: "70,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "블리칭 로션",
    tags: ["#미백 #보습 #진정 #뺄런스유지"],
    bottom: "500ml",
    price: "85,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝",
    highlight: "블리칭 미스트",
    tags: ["#미백기능성 #콜라겐생성 #비타민c"],
    bottom: "150ml",
    price: "32,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 브라이트닝 ",
    highlight: "블리칭 앰플",
    tags: ["#멜라닌억제(펩타이드34종)"],
    bottom: "50ml/500ml",
    price: "45,000원/130,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 인센티브",
    highlight: "에이씨 크림",
    tags: ["#어성초 #진정 #수분보충"],
    bottom: "15ml",
    price: "23,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인센티브 리제너레이트",
    highlight: "레티놀 크림",
    tags: ["#안티에이 #순수비타민A #PDRN"],
    bottom: "30ml",
    price: "85,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 로션",
    tags: ["#화장전 피부결 정돈 #영양","#피부 보습효과 #피부 탄력관리"],
    bottom: "150ml",
    price: "85,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 마스크팩",
    tags: ["#피부안정 #식물성워터 #수분생기"],
    bottom: "1매/10매",
    price: "4,000원/35,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 아이크림",
    tags: ["#고보습 #피부장벽강화"],
    bottom: "30ml/100ml",
    price: "48,000원/70,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션 ",
    highlight: "리페어 크림",
    tags: ["#재생 No.1(델타이드33종)","#PDRN #EGF #글루타티온"],
    bottom: "15ml/250ml",
    price: "35,000원/98,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "리페어 토너",
    tags: ["#PDRN #병풀 #판테놀","#보습 #영양 #밸런스유지"],
    bottom: "1,000ml",
    price: "70,000원",
    color: "repair",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "케이 크림",
    tags: ["#피부진정 #녹차추출물 #펩타이드"],
    bottom: "50ml / 500ml",
    price: "50,000원 / 120,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "포밍 케이 클렌저",
    tags: ["#복합히알루론산 #병풀 #마데카소","#촉촉한 클렌징 #말끔한 클렌징"],
    bottom: "120ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브",
    highlight: "케이 앰플",
    tags: ["#병풀잎 #엑소좀 #5가지 펩타이드"],
    bottom: "30ml/500ml",
    price: "50,000원/130,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브  ",
    highlight: "퓨리파잉 토너",
    tags: ["#티트리잎수함유 # 피부안정 #보습"],
    bottom: "1000ml",
    price: "70,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 미스트",
    tags: ["#티트리추출물 #진정 #보습"],
    bottom: "150ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 로션",
    tags: ["#마데카소사이드 #보습 #진정"],
    bottom: "500ml",
    price: "80,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 앰플",
    tags: ["#병풀 #편백수 #티트리추출물"],
    bottom: "50ml/500ml",
    price: "45,000원/130,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "센시티브",
    highlight: "퓨리파잉 클렌저",
    tags: ["#티트리추출물함유 #피지량조절"],
    bottom: "1000ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "리네이처레이션",
    highlight: "베리어 케이 미스트",
    tags: ["#지친 피부에 활력","#K3 #밸런스 #보습 #콜라겐생성"],
    bottom: "150ml",
    price: "32,000원",
    color: "k",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 솔루션",
    tags: ["#피부컨디션저하 시 #마데카소","#구아이아줄렌 #병풀 #어성초"],
    bottom: "120ml",
    price: "90,000원",
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "아줄렌",
    highlight: "시카 크림",
    tags: ["#피부톤개선 #영양충전 #아줄렌","#PDRN #어성초"],
    bottom: "70ml",
    price: "85,000원",
    color: "cica",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 미스트",
    tags: ["#쿨링 #진정 #보습"],
    bottom: "150ml",
    price: "32,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 토너",
    tags: ["#판테놀함유 #쿨링 #진정 #병풀"],
    bottom: "1000ml",
    price: "70,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 앰플",
    tags: ["#판테놀함유 #수분충전 #피부보습"],
    bottom: "50ml/100ml",
    price: "45,000원/130,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 로션",
    tags: ["#판테놀함유 #수분충전 #피부보습"],
    bottom: "500ml",
    price: "130,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "모이스처라이징",
    highlight: "히알루론 크림",
    tags: ["#진정 #보습 #탄력 #밸런스유지"],
    bottom: "50ml/250ml",
    price: "40,000원/98,000원",
    color: "hyaluron",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "바이오 인텐시브",
    highlight: "블레미쉬밤",
    tags: ["#피부케어 #영양보충 #수분보충"],
    bottom: "50ml",
    price: "50,000원",
    color: "sun",
  },
  {
    brand: "유쏘랩",
    line: "바이오",
    title: "인텐시브 리제너레이트",
    highlight: "레티놀 앰플",
    tags: ["#주름개선 #모공탄력 #안티에이징","#턴오버주기 #세포재생주기"],
    color: "retinol",
  },
];

export const INITIAL_PRODUCT_SHEET_CARDS = withIds(RAW);

export const PRODUCT_SHEET_CARD_COUNT = INITIAL_PRODUCT_SHEET_CARDS.length;
